version: "3"

services:
  db:
    image: postgres:15.4
    container_name: postgres
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=template
      - POSTGRES_USER=postgres
    restart: always
    ports:
      - 5432:5432
    networks:
      - udemy-net

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: ./frontend/dev.Dockerfile
    volumes:
      - ./frontend:/app
    restart: always
    ports:
      - 3333:3000
    networks:
      - udemy-net
    tty: true
    stdin_open: true

volumes:
  db-store:

networks:
  udemy-net:
